<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * API catalog for the developer tester UI (Postman-style).
 * Mirrors lib/frontendApi.ts + key /api/mobile/* routes.
 */

$sample_user = array(
    'id' => 2,
    'name' => 'Demo Owner',
    'email' => 'owner@test.com',
    'phone' => '9888888888',
    'role' => 'owner',
    'status' => 'approved',
    'city_id' => 1,
    'profile_pic' => null,
    'api_role' => 'agent',
    'api_user_type' => 'agent',
    'is_verified' => 1,
);

$sample_property_card = array(
    'id' => 2,
    'title' => '[DEMO] Premium 3BHK Near OMR',
    'slug' => 'demo-premium-3bhk-near-omr',
    'property_type' => 'independent_villa',
    'property_type_label' => 'Independent Villa',
    'listing_type' => 'sale',
    'price' => 12500000,
    'price_formatted' => '₹1.25 Cr',
    'bedrooms' => 3,
    'bathrooms' => 3,
    'area_sqft' => 1650,
    'locality' => 'Sholinganallur',
    'city_name' => 'Chennai',
    'city_id' => 1,
    'is_featured' => 1,
    'thumbnail_url' => 'https://superfinelabels.in/cp/assets/uploads/nb_properties/sample.png',
    'image_urls' => array(
        'https://superfinelabels.in/cp/assets/uploads/nb_properties/sample.png',
    ),
    'url' => 'https://superfinelabels.in/cp/property/demo-premium-3bhk-near-omr/',
);

$sample_city = array(
    'id' => 1,
    'name' => 'Chennai',
    'state' => 'Tamil Nadu',
    'is_active' => 1,
);

$config['api_catalog'] = array(
    'version' => '1.0',
    'auth_note' => 'Send token via header: X-Api-Token: <token> or Authorization: Bearer <token>',
    'groups' => array(
        array(
            'id' => 'auth',
            'title' => 'Authentication',
            'description' => 'Used by web app (lib/frontendApi.ts) — same as mobile session token.',
            'endpoints' => array(
                array(
                    'id' => 'nb_login',
                    'name' => 'Login',
                    'method' => 'POST',
                    'path' => 'api/nb/login',
                    'auth' => false,
                    'body_type' => 'json',
                    'description' => 'Login with email or phone + password. Returns api token.',
                    'body' => array('login' => 'owner@test.com', 'password' => 'your_password'),
                    'sample_response' => array(
                        'success' => true,
                        'token' => 'a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456',
                        'user' => $sample_user,
                    ),
                ),
                array(
                    'id' => 'nb_register',
                    'name' => 'Register',
                    'method' => 'POST',
                    'path' => 'api/nb/register',
                    'auth' => false,
                    'body_type' => 'json',
                    'description' => 'Register customer/owner/agent. Required: accept_terms must be true. Use multipart only when uploading aadhar_file or profile_pic.',
                    'body' => array(
                        'name' => 'Test User',
                        'email' => 'testuser@example.com',
                        'phone' => '9876543210',
                        'password' => 'Password@123',
                        'password_confirm' => 'Password@123',
                        'role' => 'customer',
                        'city_id' => 1,
                        'accept_terms' => true,
                    ),
                    'sample_response' => array(
                        'success' => true,
                        'token' => 'a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456',
                        'user' => array_merge($sample_user, array('name' => 'Test User', 'email' => 'testuser@example.com', 'status' => 'pending')),
                        'message' => 'Registration successful. Awaiting admin approval.',
                    ),
                ),
                array(
                    'id' => 'nb_me',
                    'name' => 'Current user (Me)',
                    'method' => 'GET',
                    'path' => 'api/nb/me',
                    'auth' => true,
                    'body_type' => 'none',
                    'description' => 'Returns logged-in user from X-Api-Token.',
                    'query' => array(),
                    'sample_response' => array('success' => true, 'user' => $sample_user),
                ),
                array(
                    'id' => 'nb_logout',
                    'name' => 'Logout',
                    'method' => 'POST',
                    'path' => 'api/nb/logout',
                    'auth' => true,
                    'body_type' => 'none',
                    'description' => 'Invalidates token and session.',
                    'sample_response' => array('success' => true, 'message' => 'Logged out.'),
                ),
                array(
                    'id' => 'nb_update_profile',
                    'name' => 'Update profile',
                    'method' => 'POST',
                    'path' => 'api/nb/update-profile',
                    'auth' => true,
                    'body_type' => 'form',
                    'description' => 'Update name, phone, profile_pic, aadhar (multipart).',
                    'body' => array('name' => 'Demo Owner Updated', 'phone' => '9888888888'),
                    'sample_response' => array(
                        'success' => true,
                        'message' => 'Profile updated successfully',
                        'user' => array_merge($sample_user, array('name' => 'Demo Owner Updated')),
                    ),
                ),
            ),
        ),
        array(
            'id' => 'search',
            'title' => 'Cities & Search',
            'description' => 'Homepage, explore cities, property search — web frontend.',
            'endpoints' => array(
                array(
                    'id' => 'nb_cities',
                    'name' => 'List cities',
                    'method' => 'GET',
                    'path' => 'api/nb/cities',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array(),
                    'sample_response' => array('success' => true, 'cities' => array($sample_city)),
                ),
                array(
                    'id' => 'nb_explore_cities',
                    'name' => 'Explore cities (with counts)',
                    'method' => 'GET',
                    'path' => 'api/nb/explore-cities',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array(),
                    'sample_response' => array(
                        'success' => true,
                        'cities' => array(
                            array_merge($sample_city, array('listing_count' => 42, 'image' => 'assets/uploads/cities/chennai.jpg')),
                        ),
                    ),
                ),
                array(
                    'id' => 'nb_search',
                    'name' => 'Search properties',
                    'method' => 'GET',
                    'path' => 'api/nb/search',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array(
                        'city_id' => '1',
                        'property_type' => 'independent_villa',
                        'listing_type' => 'sale',
                        'q' => 'OMR',
                        'page' => '1',
                        'limit' => '10',
                    ),
                    'sample_response' => array(
                        'success' => true,
                        'total' => 2,
                        'page' => 1,
                        'limit' => 10,
                        'items' => array($sample_property_card),
                    ),
                ),
                array(
                    'id' => 'nb_site_banners',
                    'name' => 'Site banners',
                    'method' => 'GET',
                    'path' => 'api/nb/site-banners',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('limit' => '5'),
                    'sample_response' => array(
                        'success' => true,
                        'total' => 1,
                        'items' => array(
                            array('id' => 1, 'image' => 'assets/uploads/banners/hero.jpg', 'image_url' => 'https://superfinelabels.in/cp/assets/uploads/banners/hero.jpg'),
                        ),
                    ),
                ),
                array(
                    'id' => 'nb_home_banners',
                    'name' => 'Home banner listings',
                    'method' => 'GET',
                    'path' => 'api/nb/home-banners',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('city_id' => '1', 'limit' => '5'),
                    'sample_response' => array(
                        'success' => true,
                        'total' => 1,
                        'page' => 1,
                        'limit' => 5,
                        'items' => array($sample_property_card),
                    ),
                ),
                array(
                    'id' => 'nb_property_type_counts',
                    'name' => 'Property type counts',
                    'method' => 'GET',
                    'path' => 'api/nb/property-type-counts',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('city_id' => '1'),
                    'sample_response' => array(
                        'success' => true,
                        'counts' => array(
                            array('property_type' => 'apartment', 'label' => 'Apartment', 'count' => 15),
                            array('property_type' => 'independent_villa', 'label' => 'Independent Villa', 'count' => 8),
                        ),
                    ),
                ),
                array(
                    'id' => 'property_types',
                    'name' => 'Property types (grouped)',
                    'method' => 'GET',
                    'path' => 'api/property-types',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array(),
                    'sample_response' => array(
                        'success' => true,
                        'types' => array(
                            array('main_type' => 'residential', 'label' => 'Residential', 'sub_types' => array(
                                array('slug' => 'apartment', 'label' => 'Apartment'),
                                array('slug' => 'independent_villa', 'label' => 'Independent Villa'),
                            )),
                        ),
                    ),
                ),
                array(
                    'id' => 'property_types_flat',
                    'name' => 'Property types (flat)',
                    'method' => 'GET',
                    'path' => 'api/property-types/flat',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array(),
                    'sample_response' => array(
                        'success' => true,
                        'types' => array(
                            array('slug' => 'apartment', 'label' => 'Apartment'),
                            array('slug' => 'independent_villa', 'label' => 'Independent Villa'),
                        ),
                    ),
                ),
            ),
        ),
        array(
            'id' => 'property',
            'title' => 'Property detail & save',
            'description' => 'Public property page and owner listing form.',
            'endpoints' => array(
                array(
                    'id' => 'property_detail',
                    'name' => 'Property by slug or ID',
                    'method' => 'GET',
                    'path' => 'api/properties/demo-premium-3bhk-near-omr',
                    'auth' => false,
                    'body_type' => 'none',
                    'description' => 'Public active listing only. Replace slug in path.',
                    'sample_response' => array(
                        'success' => true,
                        'property' => array_merge($sample_property_card, array(
                            'description' => 'Corner unit, sea breeze, two covered parking.',
                            'address' => 'Tower A, OMR',
                            'amenities' => array('Lift', 'Parking', 'Security'),
                            'owner_name' => 'Demo Owner',
                            'owner_phone' => '9888888888',
                            'is_active' => 1,
                        )),
                    ),
                ),
                array(
                    'id' => 'property_save',
                    'name' => 'Save property (owner)',
                    'method' => 'POST',
                    'path' => 'api/property/save',
                    'auth' => true,
                    'body_type' => 'form',
                    'description' => 'Create/update listing. Non-admin listings need approval (is_active=0).',
                    'body' => array(
                        'title' => 'My 2BHK Apartment',
                        'listing_type' => 'rent',
                        'property_type' => 'apartment',
                        'price' => '25000',
                        'address' => '123 Main Street, Peelamedu',
                        'city_id' => '1',
                        'locality' => 'Peelamedu',
                        'bedrooms' => '2',
                        'bathrooms' => '2',
                        'area_sqft' => '1100',
                    ),
                    'sample_response' => array(
                        'success' => true,
                        'message' => 'Property saved. Pending admin approval before it appears on the site.',
                        'property_id' => 31,
                        'slug' => 'my-2bhk-apartment',
                    ),
                ),
            ),
        ),
        array(
            'id' => 'wishlist',
            'title' => 'Wishlist & Enquiry',
            'description' => 'Buyer wishlist and property enquiries.',
            'endpoints' => array(
                array(
                    'id' => 'wishlist_list',
                    'name' => 'Get wishlist',
                    'method' => 'GET',
                    'path' => 'api/nb/wishlist',
                    'auth' => true,
                    'body_type' => 'none',
                    'query' => array('userId' => '3'),
                    'sample_response' => array(
                        'success' => true,
                        'items' => array($sample_property_card),
                    ),
                ),
                array(
                    'id' => 'wishlist_check',
                    'name' => 'Check wishlist status',
                    'method' => 'GET',
                    'path' => 'api/nb/wishlist/check',
                    'auth' => true,
                    'body_type' => 'none',
                    'query' => array('property_id' => '2', 'userId' => '3'),
                    'sample_response' => array('success' => true, 'wishlisted' => true),
                ),
                array(
                    'id' => 'wishlist_toggle',
                    'name' => 'Toggle wishlist',
                    'method' => 'POST',
                    'path' => 'api/nb/wishlist/toggle',
                    'auth' => true,
                    'body_type' => 'json',
                    'body' => array('property_id' => 2, 'userId' => 3),
                    'sample_response' => array('success' => true, 'wishlisted' => true, 'message' => 'Added to wishlist'),
                ),
                array(
                    'id' => 'enquiry',
                    'name' => 'Submit enquiry',
                    'method' => 'POST',
                    'path' => 'api/nb/enquiry',
                    'auth' => true,
                    'body_type' => 'json',
                    'body' => array(
                        'property_id' => 2,
                        'user_id' => 3,
                        'name' => 'Buyer Name',
                        'email' => 'buyer@test.com',
                        'phone' => '9123456789',
                        'message' => 'I am interested in this property.',
                    ),
                    'sample_response' => array(
                        'success' => true,
                        'message' => 'Enquiry sent successfully.',
                        'enquiry_id' => 15,
                    ),
                ),
            ),
        ),
        array(
            'id' => 'dashboard',
            'title' => 'Owner & Tenant dashboards',
            'description' => 'Web dashboard APIs (Api_web.php). Requires auth token.',
            'endpoints' => array(
                array(
                    'id' => 'owner_dashboard',
                    'name' => 'Owner dashboard stats',
                    'method' => 'GET',
                    'path' => 'api/owner/dashboard',
                    'auth' => true,
                    'body_type' => 'none',
                    'sample_response' => array(
                        'success' => true,
                        'stats' => array(
                            'total_listings' => 5,
                            'active_listings' => 3,
                            'total_views' => 120,
                            'enquiry_count' => 8,
                        ),
                        'recent_enquiries' => array(
                            array('id' => 1, 'property_title' => '[DEMO] Premium 3BHK', 'tenant_name' => 'Buyer', 'created_at' => '2026-06-20 10:00:00'),
                        ),
                    ),
                ),
                array(
                    'id' => 'owner_listings',
                    'name' => 'Owner listings',
                    'method' => 'GET',
                    'path' => 'api/owner/listings',
                    'auth' => true,
                    'body_type' => 'none',
                    'sample_response' => array(
                        'success' => true,
                        'listings' => array(array_merge($sample_property_card, array('is_active' => 1))),
                    ),
                ),
                array(
                    'id' => 'owner_enquiries',
                    'name' => 'Owner enquiries',
                    'method' => 'GET',
                    'path' => 'api/owner/enquiries',
                    'auth' => true,
                    'body_type' => 'none',
                    'sample_response' => array(
                        'success' => true,
                        'enquiries' => array(
                            array('id' => 1, 'property_title' => '[DEMO] Premium 3BHK', 'tenant_name' => 'Buyer', 'message' => 'Interested', 'created_at' => '2026-06-20 10:00:00'),
                        ),
                    ),
                ),
                array(
                    'id' => 'tenant_enquiries',
                    'name' => 'Tenant enquiries',
                    'method' => 'GET',
                    'path' => 'api/tenant/enquiries',
                    'auth' => true,
                    'body_type' => 'none',
                    'sample_response' => array(
                        'success' => true,
                        'enquiries' => array(
                            array('id' => 1, 'property_title' => '[DEMO] Premium 3BHK', 'city_name' => 'Chennai', 'created_at' => '2026-06-20 10:00:00'),
                        ),
                    ),
                ),
            ),
        ),
        array(
            'id' => 'content',
            'title' => 'Blogs, Feedback & Live updates',
            'description' => 'Content and user feedback endpoints.',
            'endpoints' => array(
                array(
                    'id' => 'blogs_list',
                    'name' => 'List blogs',
                    'method' => 'GET',
                    'path' => 'api/blogs',
                    'auth' => false,
                    'body_type' => 'none',
                    'sample_response' => array(
                        'success' => true,
                        'blogs' => array(
                            array('id' => 1, 'title' => 'Coimbatore Real Estate Trends', 'slug' => 'coimbatore-trends', 'excerpt' => 'Market overview...'),
                        ),
                    ),
                ),
                array(
                    'id' => 'blog_detail',
                    'name' => 'Blog by ID',
                    'method' => 'GET',
                    'path' => 'api/blogs',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('id' => '1'),
                    'sample_response' => array(
                        'success' => true,
                        'blog' => array('id' => 1, 'title' => 'Coimbatore Real Estate Trends', 'content' => '<p>Full article HTML...</p>'),
                    ),
                ),
                array(
                    'id' => 'feedback_list',
                    'name' => 'List feedback (auth)',
                    'method' => 'GET',
                    'path' => 'api/feedback',
                    'auth' => true,
                    'body_type' => 'none',
                    'sample_response' => array(
                        'success' => true,
                        'feedbacks' => array(
                            array('id' => 1, 'title' => 'Great app', 'message' => 'Easy to search properties', 'created_at' => '2026-06-01 12:00:00'),
                        ),
                    ),
                ),
                array(
                    'id' => 'feedback_submit',
                    'name' => 'Submit feedback',
                    'method' => 'POST',
                    'path' => 'api/feedback',
                    'auth' => true,
                    'body_type' => 'form',
                    'body' => array('title' => 'Suggestion', 'message' => 'Add map filter', 'rating' => '5'),
                    'sample_response' => array('success' => true, 'message' => 'Feedback submitted'),
                ),
                array(
                    'id' => 'live_update_create',
                    'name' => 'Create live update',
                    'method' => 'POST',
                    'path' => 'api/mobile/live-updates/create',
                    'auth' => true,
                    'body_type' => 'form',
                    'body' => array('caption' => 'Visited this property today', 'user_id' => '3'),
                    'sample_response' => array('success' => true, 'message' => 'Live update posted', 'id' => 10),
                ),
                array(
                    'id' => 'notifications',
                    'name' => 'Notifications',
                    'method' => 'GET',
                    'path' => 'api/nb/notifications',
                    'auth' => true,
                    'body_type' => 'none',
                    'sample_response' => array(
                        'success' => true,
                        'notifications' => array(
                            array('id' => 1, 'title' => 'Enquiry received', 'body' => 'Someone enquired on your listing', 'is_read' => 0),
                        ),
                    ),
                ),
            ),
        ),
        array(
            'id' => 'mobile',
            'title' => 'Mobile app APIs',
            'description' => 'Native app routes under /api/mobile/* (OTP auth, CRUD, etc.).',
            'endpoints' => array(
                array(
                    'id' => 'mobile_home',
                    'name' => 'Mobile home',
                    'method' => 'GET',
                    'path' => 'api/mobile/home',
                    'auth' => false,
                    'body_type' => 'none',
                    'sample_response' => array(
                        'success' => true,
                        'banners' => array(),
                        'featured' => array($sample_property_card),
                        'latest' => array($sample_property_card),
                    ),
                ),
                array(
                    'id' => 'mobile_properties',
                    'name' => 'Mobile properties list',
                    'method' => 'GET',
                    'path' => 'api/mobile/properties',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('page' => '1', 'limit' => '20'),
                    'sample_response' => array('success' => true, 'data' => array($sample_property_card), 'total' => 50),
                ),
                array(
                    'id' => 'mobile_search',
                    'name' => 'Mobile property search',
                    'method' => 'GET',
                    'path' => 'api/mobile/properties/search',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('city_id' => '1', 'keyword' => 'OMR'),
                    'sample_response' => array('success' => true, 'data' => array($sample_property_card)),
                ),
                array(
                    'id' => 'mobile_property',
                    'name' => 'Mobile property detail',
                    'method' => 'GET',
                    'path' => 'api/mobile/properties/2',
                    'auth' => false,
                    'body_type' => 'none',
                    'sample_response' => array('success' => true, 'data' => $sample_property_card),
                ),
                array(
                    'id' => 'mobile_cities',
                    'name' => 'Mobile cities',
                    'method' => 'GET',
                    'path' => 'api/mobile/cities',
                    'auth' => false,
                    'body_type' => 'none',
                    'sample_response' => array('success' => true, 'data' => array($sample_city)),
                ),
                array(
                    'id' => 'mobile_send_otp',
                    'name' => 'Send OTP',
                    'method' => 'POST',
                    'path' => 'api/mobile/send_otp',
                    'auth' => false,
                    'body_type' => 'json',
                    'body' => array('phone' => '9876543210'),
                    'sample_response' => array('success' => true, 'message' => 'OTP sent', 'otp' => '123456'),
                ),
                array(
                    'id' => 'mobile_verify_otp',
                    'name' => 'Verify OTP',
                    'method' => 'POST',
                    'path' => 'api/mobile/verify_otp',
                    'auth' => false,
                    'body_type' => 'json',
                    'body' => array('phone' => '9876543210', 'otp' => '123456'),
                    'sample_response' => array('success' => true, 'token' => 'mobile_session_token', 'user' => $sample_user),
                ),
                array(
                    'id' => 'mobile_profile',
                    'name' => 'Mobile profile',
                    'method' => 'GET',
                    'path' => 'api/mobile/profile',
                    'auth' => true,
                    'body_type' => 'none',
                    'query' => array('userId' => '2'),
                    'sample_response' => array('success' => true, 'user' => $sample_user),
                ),
                array(
                    'id' => 'mobile_wishlist',
                    'name' => 'Mobile wishlist',
                    'method' => 'GET',
                    'path' => 'api/mobile/wishlist',
                    'auth' => true,
                    'body_type' => 'none',
                    'query' => array('userId' => '3'),
                    'sample_response' => array('success' => true, 'data' => array($sample_property_card)),
                ),
                array(
                    'id' => 'mobile_enquiry',
                    'name' => 'Mobile enquiry',
                    'method' => 'POST',
                    'path' => 'api/mobile/enquiry',
                    'auth' => true,
                    'body_type' => 'json',
                    'body' => array('property_id' => 2, 'user_id' => 3, 'message' => 'Interested'),
                    'sample_response' => array('success' => true, 'message' => 'Enquiry submitted'),
                ),
                array(
                    'id' => 'mobile_blogs',
                    'name' => 'Mobile blogs',
                    'method' => 'GET',
                    'path' => 'api/mobile/blogs',
                    'auth' => false,
                    'body_type' => 'none',
                    'sample_response' => array('success' => true, 'data' => array(array('id' => 1, 'title' => 'News article'))),
                ),
            ),
        ),
    ),
);
