<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * API catalog for the developer tester UI (Postman-style).
 * Mirrors lib/frontendApi.ts + key /api/mobile/* routes.
 */

$sample_user = array(
    'id' => 2,
    'name' => 'Demo Owner',
    'email' => 'owner@test.com',
    'phone' => '9888888888',
    'role' => 'owner',
    'status' => 'approved',
    'city_id' => 1,
    'profile_pic' => null,
    'api_role' => 'agent',
    'api_user_type' => 'agent',
    'is_verified' => 1,
);

$sample_property_card = array(
    'id' => 2,
    'title' => '[DEMO] Premium 3BHK Near OMR',
    'slug' => 'demo-premium-3bhk-near-omr',
    'property_type' => 'independent_villa',
    'property_type_label' => 'Independent Villa',
    'listing_type' => 'sale',
    'price' => 12500000,
    'price_formatted' => '₹1.25 Cr',
    'bedrooms' => 3,
    'bathrooms' => 3,
    'area_sqft' => 1650,
    'locality' => 'Sholinganallur',
    'city_name' => 'Chennai',
    'city_id' => 1,
    'is_featured' => 1,
    'thumbnail_url' => 'https://superfinelabels.in/cp/assets/uploads/nb_properties/sample.png',
    'image_urls' => array(
        'https://superfinelabels.in/cp/assets/uploads/nb_properties/sample.png',
    ),
    'url' => 'https://superfinelabels.in/cp/property/demo-premium-3bhk-near-omr/',
);

$sample_city = array(
    'id' => 1,
    'name' => 'Chennai',
    'state' => 'Tamil Nadu',
    'is_active' => 1,
);

$sample_youtube_media = array(
    'id' => 1,
    'title' => 'Sample Property Tour',
    'videoUrl' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    'youtube_id' => 'dQw4w9WgXcQ',
    'embed_url' => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    'thumbnail' => 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    'status' => 'active',
    'index_no' => 1,
    'createdAt' => '2026-06-01 10:00:00',
);

$homepage_section_list_response = array(
    'success' => true,
    'data' => array($sample_property_card),
    'total' => 1,
    'limit' => 20,
    'offset' => 0,
    'page' => 1,
);

$config['api_catalog'] = array(
    'version' => '1.0',
    'auth_note' => 'Send token via header: X-Api-Token: <token> or Authorization: Bearer <token>',
    'groups' => array(
        array(
            'id' => 'auth',
            'title' => 'Authentication',
            'description' => 'Phone OTP login (WhatsApp via AskEva) + admin email login. Web app uses send-otp / verify-otp / resend-otp.',
            'endpoints' => array(
                array(
                    'id' => 'nb_login',
                    'name' => 'Login',
                    'method' => 'POST',
                    'path' => 'api/nb/login',
                    'auth' => false,
                    'body_type' => 'json',
                    'description' => 'Email + password login for approved owner, tenant, agent, and admin accounts. Phone sign-in uses Send OTP + Verify OTP.',
                    'body' => array('login' => 'owner@test.com', 'password' => 'your_password'),
                    'sample_response' => array(
                        'success' => true,
                        'token' => 'a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456',
                        'user' => $sample_user,
                    ),
                ),
                array(
                    'id' => 'nb_register',
                    'name' => 'Register',
                    'method' => 'POST',
                    'path' => 'api/nb/register',
                    'auth' => false,
                    'body_type' => 'json',
                    'description' => 'Register as agent, tenant, or owner. role: agent | tenant | owner. Agent requires aadhar_no (12 digits) + aadhar_file. Aliases: aadhaar_no, aadhar_number.',
                    'body' => array(
                        'name' => 'Test User',
                        'email' => 'testuser@example.com',
                        'phone' => '9876543210',
                        'password' => 'Password@123',
                        'password_confirm' => 'Password@123',
                        'role' => 'agent',
                        'aadhar_no' => '123456789012',
                        'city_id' => 1,
                        'accept_terms' => true,
                    ),
                    'sample_response' => array(
                        'success' => true,
                        'token' => 'a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456',
                        'user' => array_merge($sample_user, array('name' => 'Test User', 'email' => 'testuser@example.com', 'status' => 'pending')),
                        'message' => 'Registration successful. Awaiting admin approval.',
                    ),
                ),
                array(
                    'id' => 'nb_me',
                    'name' => 'Current user (Me)',
                    'method' => 'GET',
                    'path' => 'api/nb/me',
                    'auth' => true,
                    'body_type' => 'none',
                    'description' => 'Returns logged-in user from X-Api-Token.',
                    'query' => array(),
                    'sample_response' => array('success' => true, 'user' => $sample_user),
                ),
                array(
                    'id' => 'nb_logout',
                    'name' => 'Logout',
                    'method' => 'POST',
                    'path' => 'api/nb/logout',
                    'auth' => true,
                    'body_type' => 'none',
                    'query' => array(),
                    'description' => 'Invalidates token and session. Send X-Api-Token header only.',
                    'sample_response' => array('success' => true, 'message' => 'Logged out.'),
                ),
                array(
                    'id' => 'nb_send_otp',
                    'name' => 'Send OTP (WhatsApp login)',
                    'method' => 'POST',
                    'path' => 'api/nb/send-otp',
                    'auth' => false,
                    'body_type' => 'json',
                    'description' => 'Send 4-digit OTP to a registered user phone via AskEva WhatsApp (authentication template). Phone must exist in nb_users and be approved. Test phone 9876543210 skips WhatsApp and always uses OTP 1234.',
                    'body' => array('phone' => '9876543210', 'country_code' => '+91'),
                    'sample_response' => array(
                        'success' => true,
                        'message' => 'OTP sent to your WhatsApp number.',
                        'expires_in' => 300,
                        'development_mode' => true,
                        'otp' => '1234',
                    ),
                ),
                array(
                    'id' => 'nb_verify_otp',
                    'name' => 'Verify OTP & sign in',
                    'method' => 'POST',
                    'path' => 'api/nb/verify-otp',
                    'auth' => false,
                    'body_type' => 'json',
                    'description' => 'Verify 4-digit OTP and return session token + user. Use after Send OTP. Test: phone 9876543210, otp 1234.',
                    'body' => array('phone' => '9876543210', 'country_code' => '+91', 'otp' => '1234'),
                    'sample_response' => array(
                        'success' => true,
                        'message' => 'Signed in successfully.',
                        'token' => 'a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456',
                        'user' => $sample_user,
                    ),
                ),
                array(
                    'id' => 'nb_resend_otp',
                    'name' => 'Resend OTP',
                    'method' => 'POST',
                    'path' => 'api/nb/resend-otp',
                    'auth' => false,
                    'body_type' => 'json',
                    'description' => 'Same as Send OTP — generates a new 4-digit OTP and sends via WhatsApp.',
                    'body' => array('phone' => '9876543210', 'country_code' => '+91'),
                    'sample_response' => array(
                        'success' => true,
                        'message' => 'OTP sent to your WhatsApp number.',
                        'expires_in' => 300,
                        'development_mode' => true,
                        'otp' => '1234',
                    ),
                ),
                array(
                    'id' => 'nb_forgot_password',
                    'name' => 'Forgot password',
                    'method' => 'POST',
                    'path' => 'api/nb/forgot-password',
                    'auth' => false,
                    'body_type' => 'json',
                    'description' => 'Send OTP to registered phone for password reset. Use login = email or phone.',
                    'body' => array('login' => 'owner@test.com', 'country_code' => '+91'),
                    'sample_response' => array(
                        'success' => true,
                        'message' => 'OTP sent to your registered WhatsApp number.',
                        'phone_masked' => '98******10',
                        'expires_in' => 300,
                        'development_mode' => true,
                        'otp' => '1234',
                    ),
                ),
                array(
                    'id' => 'nb_reset_password',
                    'name' => 'Reset password (OTP)',
                    'method' => 'POST',
                    'path' => 'api/nb/reset-password',
                    'auth' => false,
                    'body_type' => 'json',
                    'description' => 'Set new password after Forgot password OTP.',
                    'body' => array(
                        'login' => 'owner@test.com',
                        'otp' => '1234',
                        'password' => 'NewPass@123',
                        'password_confirm' => 'NewPass@123',
                    ),
                    'sample_response' => array(
                        'success' => true,
                        'message' => 'Password updated successfully.',
                        'token' => 'a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456',
                        'user' => $sample_user,
                    ),
                ),
                array(
                    'id' => 'nb_change_password',
                    'name' => 'Change password',
                    'method' => 'POST',
                    'path' => 'api/nb/change-password',
                    'auth' => true,
                    'body_type' => 'json',
                    'description' => 'Change password while logged in. Requires current_password and new_password.',
                    'body' => array(
                        'current_password' => 'your_old_password',
                        'new_password' => 'NewPass@123',
                        'new_password_confirm' => 'NewPass@123',
                    ),
                    'sample_response' => array('success' => true, 'message' => 'Password changed successfully.'),
                ),
                array(
                    'id' => 'nb_update_profile',
                    'name' => 'Update profile',
                    'method' => 'POST',
                    'path' => 'api/nb/update-profile',
                    'auth' => true,
                    'body_type' => 'form',
                    'description' => 'Update name, phone, profile_pic, aadhar (multipart).',
                    'body' => array('name' => 'Demo Owner Updated', 'phone' => '9888888888'),
                    'sample_response' => array(
                        'success' => true,
                        'message' => 'Profile updated successfully',
                        'user' => array_merge($sample_user, array('name' => 'Demo Owner Updated')),
                    ),
                ),
            ),
        ),
        array(
            'id' => 'search',
            'title' => 'Cities & Search',
            'description' => 'Homepage, explore cities, property search — web frontend.',
            'endpoints' => array(
                array(
                    'id' => 'nb_cities',
                    'name' => 'List cities',
                    'method' => 'GET',
                    'path' => 'api/nb/cities',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array(),
                    'sample_response' => array('success' => true, 'cities' => array($sample_city)),
                ),
                array(
                    'id' => 'nb_explore_cities',
                    'name' => 'Explore cities (with counts)',
                    'method' => 'GET',
                    'path' => 'api/nb/explore-cities',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array(),
                    'sample_response' => array(
                        'success' => true,
                        'cities' => array(
                            array_merge($sample_city, array('listing_count' => 42, 'image' => 'assets/uploads/cities/chennai.jpg')),
                        ),
                    ),
                ),
                array(
                    'id' => 'nb_search',
                    'name' => 'Search properties',
                    'method' => 'GET',
                    'path' => 'api/nb/search',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array(
                        'city_id' => '1',
                        'property_type' => 'independent_villa',
                        'listing_type' => 'sale',
                        'q' => 'OMR',
                        'page' => '1',
                        'limit' => '10',
                    ),
                    'sample_response' => array(
                        'success' => true,
                        'total' => 2,
                        'page' => 1,
                        'limit' => 10,
                        'items' => array($sample_property_card),
                    ),
                ),
                array(
                    'id' => 'nb_site_banners',
                    'name' => 'Site banners',
                    'method' => 'GET',
                    'path' => 'api/nb/site-banners',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('limit' => '5'),
                    'sample_response' => array(
                        'success' => true,
                        'total' => 1,
                        'items' => array(
                            array('id' => 1, 'image' => 'assets/uploads/banners/hero.jpg', 'image_url' => 'https://superfinelabels.in/cp/assets/uploads/banners/hero.jpg'),
                        ),
                    ),
                ),
                array(
                    'id' => 'nb_home_banners',
                    'name' => 'Home banner listings',
                    'method' => 'GET',
                    'path' => 'api/nb/home-banners',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('city_id' => '1', 'limit' => '5'),
                    'sample_response' => array(
                        'success' => true,
                        'total' => 1,
                        'page' => 1,
                        'limit' => 5,
                        'items' => array($sample_property_card),
                    ),
                ),
                array(
                    'id' => 'nb_property_type_counts',
                    'name' => 'Property type counts',
                    'method' => 'GET',
                    'path' => 'api/nb/property-type-counts',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('city_id' => '1'),
                    'sample_response' => array(
                        'success' => true,
                        'counts' => array(
                            array('property_type' => 'apartment', 'label' => 'Apartment', 'count' => 15),
                            array('property_type' => 'independent_villa', 'label' => 'Independent Villa', 'count' => 8),
                        ),
                    ),
                ),
                array(
                    'id' => 'property_types',
                    'name' => 'Property types (grouped)',
                    'method' => 'GET',
                    'path' => 'api/property-types',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array(),
                    'sample_response' => array(
                        'success' => true,
                        'types' => array(
                            array('main_type' => 'residential', 'label' => 'Residential', 'image_url' => 'https://superfinelabels.in/cp/assets/uploads/property_types/residential.png', 'sub_types' => array(
                                array('slug' => 'apartment', 'label' => 'Apartment', 'image_url' => 'https://superfinelabels.in/cp/assets/uploads/property_types/apartment.png'),
                                array('slug' => 'independent_villa', 'label' => 'Independent Villa', 'image_url' => null),
                            )),
                        ),
                    ),
                ),
                array(
                    'id' => 'property_types_flat',
                    'name' => 'Property types (flat)',
                    'method' => 'GET',
                    'path' => 'api/property-types/flat',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array(),
                    'sample_response' => array(
                        'success' => true,
                        'types' => array(
                            array('slug' => 'apartment', 'label' => 'Apartment'),
                            array('slug' => 'independent_villa', 'label' => 'Independent Villa'),
                        ),
                    ),
                ),
            ),
        ),
        array(
            'id' => 'property',
            'title' => 'Property detail & save',
            'description' => 'Public property page and owner listing form.',
            'endpoints' => array(
                array(
                    'id' => 'property_detail',
                    'name' => 'Property by slug or ID',
                    'method' => 'GET',
                    'path' => 'api/properties/demo-premium-3bhk-near-omr',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array(),
                    'description' => 'Public active listing only. Replace slug in URL path.',
                    'sample_request' => array(
                        'path' => 'api/properties/{slug-or-id}',
                        'path_example' => 'api/properties/demo-premium-3bhk-near-omr',
                    ),
                    'sample_response' => array(
                        'success' => true,
                        'property' => array_merge($sample_property_card, array(
                            'description' => 'Corner unit, sea breeze, two covered parking.',
                            'address' => 'Tower A, OMR',
                            'amenities' => array('Lift', 'Parking', 'Security'),
                            'owner_name' => 'Demo Owner',
                            'owner_phone' => '9888888888',
                            'is_active' => 1,
                        )),
                    ),
                ),
                array(
                    'id' => 'property_save',
                    'name' => 'Save property (owner)',
                    'method' => 'POST',
                    'path' => 'api/property/save',
                    'auth' => true,
                    'body_type' => 'form',
                    'description' => 'Create/update listing. Non-admin listings need approval (is_active=0).',
                    'body' => array(
                        'title' => 'My 2BHK Apartment',
                        'listing_type' => 'rent',
                        'property_type' => 'apartment',
                        'price' => '25000',
                        'address' => '123 Main Street, Peelamedu',
                        'city_id' => '1',
                        'locality' => 'Peelamedu',
                        'bedrooms' => '2',
                        'bathrooms' => '2',
                        'area_sqft' => '1100',
                    ),
                    'sample_response' => array(
                        'success' => true,
                        'message' => 'Property saved. Pending admin approval before it appears on the site.',
                        'property_id' => 31,
                        'slug' => 'my-2bhk-apartment',
                    ),
                ),
            ),
        ),
        array(
            'id' => 'wishlist',
            'title' => 'Wishlist & Enquiry',
            'description' => 'Buyer wishlist and property enquiries.',
            'endpoints' => array(
                array(
                    'id' => 'wishlist_list',
                    'name' => 'Get wishlist',
                    'method' => 'GET',
                    'path' => 'api/nb/wishlist',
                    'auth' => true,
                    'body_type' => 'none',
                    'query' => array('userId' => '3'),
                    'sample_response' => array(
                        'success' => true,
                        'items' => array($sample_property_card),
                    ),
                ),
                array(
                    'id' => 'wishlist_check',
                    'name' => 'Check wishlist status',
                    'method' => 'GET',
                    'path' => 'api/nb/wishlist/check',
                    'auth' => true,
                    'body_type' => 'none',
                    'query' => array('property_id' => '2', 'userId' => '3'),
                    'sample_response' => array('success' => true, 'wishlisted' => true),
                ),
                array(
                    'id' => 'wishlist_toggle',
                    'name' => 'Toggle wishlist',
                    'method' => 'POST',
                    'path' => 'api/nb/wishlist/toggle',
                    'auth' => true,
                    'body_type' => 'json',
                    'body' => array('property_id' => 2, 'userId' => 3),
                    'sample_response' => array('success' => true, 'wishlisted' => true, 'message' => 'Added to wishlist'),
                ),
                array(
                    'id' => 'enquiry',
                    'name' => 'Submit enquiry',
                    'method' => 'POST',
                    'path' => 'api/nb/enquiry',
                    'auth' => true,
                    'body_type' => 'json',
                    'body' => array(
                        'property_id' => 2,
                        'user_id' => 3,
                        'name' => 'Buyer Name',
                        'email' => 'buyer@test.com',
                        'phone' => '9123456789',
                        'message' => 'I am interested in this property.',
                    ),
                    'sample_response' => array(
                        'success' => true,
                        'message' => 'Enquiry sent successfully.',
                        'enquiry_id' => 15,
                    ),
                ),
            ),
        ),
        array(
            'id' => 'dashboard',
            'title' => 'Owner & Tenant dashboards',
            'description' => 'Web dashboard APIs (Api_web.php). Requires auth token.',
            'endpoints' => array(
                array(
                    'id' => 'owner_dashboard',
                    'name' => 'Owner dashboard stats',
                    'method' => 'GET',
                    'path' => 'api/owner/dashboard',
                    'auth' => true,
                    'body_type' => 'none',
                    'query' => array(),
                    'description' => 'Owner stats. Requires approved owner account token.',
                    'sample_response' => array(
                        'success' => true,
                        'stats' => array(
                            'total_listings' => 5,
                            'active_listings' => 3,
                            'total_views' => 120,
                            'enquiry_count' => 8,
                        ),
                        'recent_enquiries' => array(
                            array('id' => 1, 'property_title' => '[DEMO] Premium 3BHK', 'tenant_name' => 'Buyer', 'created_at' => '2026-06-20 10:00:00'),
                        ),
                    ),
                ),
                array(
                    'id' => 'owner_listings',
                    'name' => 'Owner listings',
                    'method' => 'GET',
                    'path' => 'api/owner/listings',
                    'auth' => true,
                    'body_type' => 'none',
                    'query' => array(),
                    'sample_response' => array(
                        'success' => true,
                        'listings' => array(array_merge($sample_property_card, array('is_active' => 1))),
                    ),
                ),
                array(
                    'id' => 'owner_enquiries',
                    'name' => 'Owner enquiries',
                    'method' => 'GET',
                    'path' => 'api/owner/enquiries',
                    'auth' => true,
                    'body_type' => 'none',
                    'query' => array(),
                    'sample_response' => array(
                        'success' => true,
                        'enquiries' => array(
                            array('id' => 1, 'property_title' => '[DEMO] Premium 3BHK', 'tenant_name' => 'Buyer', 'message' => 'Interested', 'created_at' => '2026-06-20 10:00:00'),
                        ),
                    ),
                ),
                array(
                    'id' => 'tenant_enquiries',
                    'name' => 'Tenant enquiries',
                    'method' => 'GET',
                    'path' => 'api/tenant/enquiries',
                    'auth' => true,
                    'body_type' => 'none',
                    'query' => array(),
                    'sample_response' => array(
                        'success' => true,
                        'enquiries' => array(
                            array('id' => 1, 'property_title' => '[DEMO] Premium 3BHK', 'city_name' => 'Chennai', 'created_at' => '2026-06-20 10:00:00'),
                        ),
                    ),
                ),
            ),
        ),
        array(
            'id' => 'content',
            'title' => 'Blogs, Feedback & Live updates',
            'description' => 'Content and user feedback endpoints.',
            'endpoints' => array(
                array(
                    'id' => 'blogs_list',
                    'name' => 'List blogs',
                    'method' => 'GET',
                    'path' => 'api/blogs',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array(),
                    'sample_response' => array(
                        'success' => true,
                        'blogs' => array(
                            array('id' => 1, 'title' => 'Coimbatore Real Estate Trends', 'slug' => 'coimbatore-trends', 'excerpt' => 'Market overview...'),
                        ),
                    ),
                ),
                array(
                    'id' => 'blog_detail',
                    'name' => 'Blog by ID',
                    'method' => 'GET',
                    'path' => 'api/blogs',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('id' => '1'),
                    'sample_response' => array(
                        'success' => true,
                        'blog' => array('id' => 1, 'title' => 'Coimbatore Real Estate Trends', 'content' => '<p>Full article HTML...</p>'),
                    ),
                ),
                array(
                    'id' => 'feedback_list',
                    'name' => 'List feedback (auth)',
                    'method' => 'GET',
                    'path' => 'api/feedback',
                    'auth' => true,
                    'body_type' => 'none',
                    'query' => array(),
                    'sample_response' => array(
                        'success' => true,
                        'feedbacks' => array(
                            array('id' => 1, 'title' => 'Great app', 'message' => 'Easy to search properties', 'created_at' => '2026-06-01 12:00:00'),
                        ),
                    ),
                ),
                array(
                    'id' => 'feedback_submit',
                    'name' => 'Submit feedback',
                    'method' => 'POST',
                    'path' => 'api/feedback',
                    'auth' => true,
                    'body_type' => 'form',
                    'body' => array('title' => 'Suggestion', 'message' => 'Add map filter', 'rating' => '5'),
                    'sample_response' => array('success' => true, 'message' => 'Feedback submitted'),
                ),
                array(
                    'id' => 'live_update_create',
                    'name' => 'Create live update',
                    'method' => 'POST',
                    'path' => 'api/mobile/live-updates/create',
                    'auth' => true,
                    'body_type' => 'form',
                    'body' => array('caption' => 'Visited this property today', 'user_id' => '3'),
                    'sample_response' => array('success' => true, 'message' => 'Live update posted', 'id' => 10),
                ),
                array(
                    'id' => 'notifications',
                    'name' => 'Notifications',
                    'method' => 'GET',
                    'path' => 'api/nb/notifications',
                    'auth' => true,
                    'body_type' => 'none',
                    'query' => array('status' => 'active', 'limit' => '20'),
                    'sample_response' => array(
                        'success' => true,
                        'notifications' => array(
                            array('id' => 1, 'title' => 'Enquiry received', 'body' => 'Someone enquired on your listing', 'is_read' => 0),
                        ),
                    ),
                ),
            ),
        ),
        array(
            'id' => 'mobile',
            'title' => 'Mobile app APIs',
            'description' => 'Native app routes under /api/mobile/* (OTP auth, CRUD, etc.).',
            'endpoints' => array(
                array(
                    'id' => 'mobile_home',
                    'name' => 'Mobile home',
                    'method' => 'GET',
                    'path' => 'api/mobile/home',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array(),
                    'sample_response' => array(
                        'success' => true,
                        'banners' => array(),
                        'featured' => array($sample_property_card),
                        'latest' => array($sample_property_card),
                    ),
                ),
                array(
                    'id' => 'mobile_properties',
                    'name' => 'Mobile properties list',
                    'method' => 'GET',
                    'path' => 'api/mobile/properties',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('page' => '1', 'limit' => '20'),
                    'sample_response' => array('success' => true, 'data' => array($sample_property_card), 'total' => 50),
                ),
                array(
                    'id' => 'mobile_search',
                    'name' => 'Mobile property search',
                    'method' => 'GET',
                    'path' => 'api/mobile/properties/search',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('city_id' => '1', 'keyword' => 'OMR'),
                    'sample_response' => array('success' => true, 'data' => array($sample_property_card)),
                ),
                array(
                    'id' => 'mobile_property',
                    'name' => 'Mobile property detail',
                    'method' => 'GET',
                    'path' => 'api/mobile/properties/2',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array(),
                    'sample_request' => array(
                        'path' => 'api/mobile/properties/{id}',
                        'path_example' => 'api/mobile/properties/2',
                    ),
                    'sample_response' => array('success' => true, 'data' => $sample_property_card),
                ),
                array(
                    'id' => 'mobile_cities',
                    'name' => 'Mobile cities',
                    'method' => 'GET',
                    'path' => 'api/mobile/cities',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array(),
                    'sample_response' => array('success' => true, 'data' => array($sample_city)),
                ),
                array(
                    'id' => 'mobile_send_otp',
                    'name' => 'Send OTP (legacy mobile)',
                    'method' => 'POST',
                    'path' => 'api/mobile/send_otp',
                    'auth' => false,
                    'body_type' => 'json',
                    'description' => 'Legacy mobile route. Web app uses api/nb/send-otp instead (same WhatsApp OTP flow).',
                    'body' => array('phone' => '9876543210', 'country_code' => '+91'),
                    'sample_response' => array('success' => true, 'message' => 'OTP sent', 'otp' => '1234'),
                ),
                array(
                    'id' => 'mobile_verify_otp',
                    'name' => 'Verify OTP (legacy mobile)',
                    'method' => 'POST',
                    'path' => 'api/mobile/verify_otp',
                    'auth' => false,
                    'body_type' => 'json',
                    'description' => 'Legacy mobile route. Web app uses api/nb/verify-otp instead.',
                    'body' => array('phone' => '9876543210', 'country_code' => '+91', 'otp' => '1234'),
                    'sample_response' => array('success' => true, 'token' => 'mobile_session_token', 'user' => $sample_user),
                ),
                array(
                    'id' => 'mobile_profile',
                    'name' => 'Mobile profile',
                    'method' => 'GET',
                    'path' => 'api/mobile/profile',
                    'auth' => true,
                    'body_type' => 'none',
                    'query' => array('userId' => '2'),
                    'sample_response' => array('success' => true, 'user' => $sample_user),
                ),
                array(
                    'id' => 'mobile_wishlist',
                    'name' => 'Mobile wishlist',
                    'method' => 'GET',
                    'path' => 'api/mobile/wishlist',
                    'auth' => true,
                    'body_type' => 'none',
                    'query' => array('userId' => '3'),
                    'sample_response' => array('success' => true, 'data' => array($sample_property_card)),
                ),
                array(
                    'id' => 'mobile_enquiry',
                    'name' => 'Mobile enquiry',
                    'method' => 'POST',
                    'path' => 'api/mobile/enquiry',
                    'auth' => true,
                    'body_type' => 'json',
                    'body' => array(
                        'property_id' => 2,
                        'user_id' => 3,
                        'name' => 'Buyer Name',
                        'email' => 'buyer@test.com',
                        'phone' => '9123456789',
                        'message' => 'Interested in this property.',
                    ),
                    'sample_response' => array('success' => true, 'message' => 'Enquiry submitted'),
                ),
                array(
                    'id' => 'mobile_enquiries_user',
                    'name' => 'My enquiries list',
                    'method' => 'GET',
                    'path' => 'api/mobile/enquiries/user/3',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('status' => 'new', 'limit' => '20', 'offset' => '0'),
                    'sample_request' => array(
                        'path' => 'api/mobile/enquiries/user/{userId}',
                        'path_example' => 'api/mobile/enquiries/user/3',
                    ),
                    'sample_response' => array('success' => true, 'data' => array(), 'total' => 0),
                ),
                array(
                    'id' => 'mobile_properties_mine',
                    'name' => 'My property listings (by user id)',
                    'method' => 'GET',
                    'path' => 'api/mobile/properties/user/3',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('page' => '1', 'limit' => '20', 'include_pending' => '1'),
                    'description' => 'Includes pending (is_active=0) listings by default. Use is_active=1 to show published only.',
                    'sample_request' => array(
                        'path' => 'api/mobile/properties/user/{userId}',
                        'path_example' => 'api/mobile/properties/user/3',
                    ),
                    'sample_response' => array('success' => true, 'data' => array(array_merge($sample_property_card, array('publication_status' => 'pending', 'is_active' => 0))), 'total' => 1),
                ),
                array(
                    'id' => 'mobile_my_properties',
                    'name' => 'My properties (token)',
                    'method' => 'GET',
                    'path' => 'api/mobile/my-properties',
                    'auth' => true,
                    'body_type' => 'none',
                    'query' => array('limit' => '50', 'offset' => '0'),
                    'description' => 'Authenticated owner/agent listings including pending approval.',
                    'sample_response' => array(
                        'success' => true,
                        'listings' => array(array_merge($sample_property_card, array('publication_status' => 'pending'))),
                        'total' => 1,
                        'stats' => array('active' => 0, 'pending' => 1),
                    ),
                ),
                array(
                    'id' => 'mobile_site_visit_schedule',
                    'name' => 'Schedule site visit',
                    'method' => 'POST',
                    'path' => 'api/mobile/site-visits/schedule',
                    'auth' => true,
                    'body_type' => 'json',
                    'body' => array(
                        'property_id' => 2,
                        'scheduled_at' => '2026-07-15 10:30:00',
                        'notes' => 'Would like to visit this weekend.',
                    ),
                    'sample_response' => array('success' => true, 'id' => 1, 'status' => 'pending', 'message' => 'Site visit scheduled. The owner will confirm shortly.'),
                ),
                array(
                    'id' => 'mobile_site_visits',
                    'name' => 'List site visits',
                    'method' => 'GET',
                    'path' => 'api/mobile/site-visits',
                    'auth' => true,
                    'body_type' => 'none',
                    'query' => array('as_owner' => '0', 'limit' => '50'),
                    'description' => 'as_owner=1 lists visits for properties you own.',
                    'sample_response' => array('success' => true, 'visits' => array()),
                ),
                array(
                    'id' => 'mobile_forgot_password',
                    'name' => 'Forgot password (mobile)',
                    'method' => 'POST',
                    'path' => 'api/mobile/forgot-password',
                    'auth' => false,
                    'body_type' => 'json',
                    'body' => array('login' => 'owner@test.com'),
                    'sample_response' => array('success' => true, 'message' => 'OTP sent to your registered WhatsApp number.', 'expires_in' => 300),
                ),
                array(
                    'id' => 'mobile_change_password',
                    'name' => 'Change password (mobile)',
                    'method' => 'POST',
                    'path' => 'api/mobile/change-password',
                    'auth' => true,
                    'body_type' => 'json',
                    'body' => array('current_password' => 'old', 'new_password' => 'NewPass@123', 'new_password_confirm' => 'NewPass@123'),
                    'sample_response' => array('success' => true, 'message' => 'Password changed successfully.'),
                ),
                array(
                    'id' => 'mobile_properties_create',
                    'name' => 'Post property (mobile)',
                    'method' => 'POST',
                    'path' => 'api/mobile/properties/create',
                    'auth' => true,
                    'body_type' => 'form',
                    'description' => 'Use multipart/form-data for images, brochure (PDF), audio_notes (mp3), location_image. JSON also supported for text fields.',
                    'body' => array(
                        'title' => '2 BHK near OMR',
                        'city_id' => 1,
                        'property_type' => 'apartment',
                        'listing_type' => 'rent',
                        'price' => 18000,
                        'address' => 'OMR Road',
                        'locality' => 'Sholinganallur',
                        'map_url' => 'https://maps.google.com/?q=12.9,80.2',
                        'location' => 'Near IT park',
                        'latitude' => '12.9010',
                        'longitude' => '80.2279',
                    ),
                    'sample_response' => array(
                        'success' => true,
                        'property_id' => 12,
                        'pending_review' => true,
                        'message' => 'Listing submitted for admin approval.',
                    ),
                ),
                array(
                    'id' => 'mobile_feedback_list',
                    'name' => 'My feedback list',
                    'method' => 'GET',
                    'path' => 'api/mobile/feedback',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('userId' => '3', 'limit' => '20', 'offset' => '0'),
                    'sample_response' => array(
                        'success' => true,
                        'data' => array(
                            'feedbacks' => array(
                                array('id' => '1', 'userId' => '3', 'title' => 'Great app', 'description' => 'Smooth experience'),
                            ),
                            'total' => 1,
                        ),
                    ),
                ),
                array(
                    'id' => 'mobile_feedback_submit',
                    'name' => 'Submit feedback',
                    'method' => 'POST',
                    'path' => 'api/mobile/feedback',
                    'auth' => false,
                    'body_type' => 'json',
                    'body' => array('userId' => 3, 'title' => 'Suggestion', 'description' => 'Add dark mode'),
                    'sample_response' => array('success' => true, 'message' => 'Feedback submitted', 'id' => 5),
                ),
                array(
                    'id' => 'mobile_blogs',
                    'name' => 'Mobile blogs (housing news)',
                    'method' => 'GET',
                    'path' => 'api/mobile/blogs',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('category' => 'market', 'limit' => '20', 'offset' => '0'),
                    'sample_response' => array('success' => true, 'data' => array(array('id' => 1, 'title' => 'News article', 'name' => 'News article')), 'total' => 1),
                ),
            ),
        ),
        array(
            'id' => 'homepage_sections',
            'title' => 'Homepage property sections',
            'description' => 'Separate list APIs for each homepage carousel/section. All return paginated property cards from nb_properties.',
            'endpoints' => array(
                array(
                    'id' => 'mobile_published',
                    'name' => 'Published properties',
                    'method' => 'GET',
                    'path' => 'api/mobile/properties/published',
                    'auth' => false,
                    'body_type' => 'none',
                    'description' => 'Active listings, newest first (same as latest).',
                    'query' => array('page' => '1', 'limit' => '20', 'city_id' => '1'),
                    'sample_response' => $homepage_section_list_response,
                ),
                array(
                    'id' => 'mobile_featured',
                    'name' => 'Featured properties',
                    'method' => 'GET',
                    'path' => 'api/mobile/properties/featured',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('page' => '1', 'limit' => '10'),
                    'sample_response' => $homepage_section_list_response,
                ),
                array(
                    'id' => 'mobile_best_rate',
                    'name' => 'Best Rate localities',
                    'method' => 'GET',
                    'path' => 'api/mobile/properties/best-rate',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('page' => '1', 'limit' => '20'),
                    'sample_response' => $homepage_section_list_response,
                ),
                array(
                    'id' => 'mobile_high_growth',
                    'name' => 'High Growth localities',
                    'method' => 'GET',
                    'path' => 'api/mobile/properties/high-growth',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('page' => '1', 'limit' => '20'),
                    'sample_response' => $homepage_section_list_response,
                ),
                array(
                    'id' => 'mobile_recommended',
                    'name' => 'Recommended properties',
                    'method' => 'GET',
                    'path' => 'api/mobile/properties/recommended',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('page' => '1', 'limit' => '20'),
                    'sample_response' => $homepage_section_list_response,
                ),
                array(
                    'id' => 'mobile_newly_launched',
                    'name' => 'Newly Launched projects',
                    'method' => 'GET',
                    'path' => 'api/mobile/properties/newly-launched',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('page' => '1', 'limit' => '20'),
                    'sample_response' => $homepage_section_list_response,
                ),
                array(
                    'id' => 'mobile_verified',
                    'name' => 'Verified properties',
                    'method' => 'GET',
                    'path' => 'api/mobile/properties/verified',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('page' => '1', 'limit' => '20'),
                    'sample_response' => $homepage_section_list_response,
                ),
                array(
                    'id' => 'mobile_premium',
                    'name' => 'Premium projects',
                    'method' => 'GET',
                    'path' => 'api/mobile/properties/premium',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('page' => '1', 'limit' => '20'),
                    'sample_response' => $homepage_section_list_response,
                ),
                array(
                    'id' => 'mobile_home_banner',
                    'name' => 'Home banner properties',
                    'method' => 'GET',
                    'path' => 'api/mobile/properties/home-banner',
                    'auth' => false,
                    'body_type' => 'none',
                    'description' => 'Properties flagged is_home_banner with home_banner_image set.',
                    'query' => array('page' => '1', 'limit' => '10'),
                    'sample_response' => $homepage_section_list_response,
                ),
            ),
        ),
        array(
            'id' => 'reels',
            'title' => 'Reels (YouTube)',
            'description' => 'Short-form reels stored in reels_videos. videoUrl must be a valid YouTube link; thumbnail is auto-generated.',
            'endpoints' => array(
                array(
                    'id' => 'reels_list',
                    'name' => 'List reels',
                    'method' => 'GET',
                    'path' => 'api/mobile/reels',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('status' => 'active'),
                    'sample_response' => array('success' => true, 'data' => array($sample_youtube_media), 'count' => 1),
                ),
                array(
                    'id' => 'reels_get',
                    'name' => 'Get reel by ID',
                    'method' => 'GET',
                    'path' => 'api/mobile/reels/1',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array(),
                    'sample_request' => array(
                        'path' => 'api/mobile/reels/{id}',
                        'path_example' => 'api/mobile/reels/1',
                    ),
                    'sample_response' => array('success' => true, 'data' => $sample_youtube_media),
                ),
                array(
                    'id' => 'reels_create',
                    'name' => 'Create reel',
                    'method' => 'POST',
                    'path' => 'api/mobile/reels/create',
                    'auth' => false,
                    'body_type' => 'json',
                    'body' => array(
                        'title' => 'New launch walkthrough',
                        'videoUrl' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                        'status' => 'active',
                    ),
                    'sample_response' => array('success' => true, 'message' => 'Reel created', 'id' => 2, 'data' => $sample_youtube_media),
                ),
                array(
                    'id' => 'reels_update',
                    'name' => 'Update reel',
                    'method' => 'POST',
                    'path' => 'api/mobile/reels/update/1',
                    'auth' => false,
                    'body_type' => 'json',
                    'body' => array(
                        'title' => 'Updated title',
                        'videoUrl' => 'https://youtu.be/dQw4w9WgXcQ',
                        'status' => 'active',
                    ),
                    'sample_request' => array(
                        'path' => 'api/mobile/reels/update/{id}',
                        'path_example' => 'api/mobile/reels/update/1',
                    ),
                    'sample_response' => array('success' => true, 'message' => 'Reel updated', 'data' => $sample_youtube_media),
                ),
                array(
                    'id' => 'reels_delete',
                    'name' => 'Delete reel',
                    'method' => 'POST',
                    'path' => 'api/mobile/reels/delete/1',
                    'auth' => false,
                    'body_type' => 'none',
                    'sample_request' => array(
                        'path' => 'api/mobile/reels/delete/{id}',
                        'path_example' => 'api/mobile/reels/delete/1',
                    ),
                    'sample_response' => array('success' => true, 'message' => 'Reel deleted'),
                ),
                array(
                    'id' => 'reels_reorder',
                    'name' => 'Reorder reels',
                    'method' => 'POST',
                    'path' => 'api/mobile/reels/reorder',
                    'auth' => false,
                    'body_type' => 'json',
                    'body' => array('orders' => array('1' => 10, '2' => 9)),
                    'sample_response' => array('success' => true, 'message' => 'Reels reordered'),
                ),
            ),
        ),
        array(
            'id' => 'videos',
            'title' => 'Videos (YouTube)',
            'description' => 'Property videos stored in videos table. Same YouTube URL rules as reels.',
            'endpoints' => array(
                array(
                    'id' => 'videos_list',
                    'name' => 'List videos',
                    'method' => 'GET',
                    'path' => 'api/mobile/videos',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array('status' => 'active'),
                    'sample_response' => array('success' => true, 'data' => array($sample_youtube_media), 'count' => 1),
                ),
                array(
                    'id' => 'videos_get',
                    'name' => 'Get video by ID',
                    'method' => 'GET',
                    'path' => 'api/mobile/videos/1',
                    'auth' => false,
                    'body_type' => 'none',
                    'query' => array(),
                    'sample_request' => array(
                        'path' => 'api/mobile/videos/{id}',
                        'path_example' => 'api/mobile/videos/1',
                    ),
                    'sample_response' => array('success' => true, 'data' => $sample_youtube_media),
                ),
                array(
                    'id' => 'videos_create',
                    'name' => 'Create video',
                    'method' => 'POST',
                    'path' => 'api/mobile/videos/create',
                    'auth' => false,
                    'body_type' => 'json',
                    'body' => array(
                        'title' => 'Project overview',
                        'videoUrl' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                        'status' => 'active',
                    ),
                    'sample_response' => array('success' => true, 'message' => 'Video created', 'id' => 2, 'data' => $sample_youtube_media),
                ),
                array(
                    'id' => 'videos_update',
                    'name' => 'Update video',
                    'method' => 'POST',
                    'path' => 'api/mobile/videos/update/1',
                    'auth' => false,
                    'body_type' => 'json',
                    'body' => array(
                        'title' => 'Updated overview',
                        'videoUrl' => 'https://youtube.com/shorts/dQw4w9WgXcQ',
                        'status' => 'active',
                    ),
                    'sample_request' => array(
                        'path' => 'api/mobile/videos/update/{id}',
                        'path_example' => 'api/mobile/videos/update/1',
                    ),
                    'sample_response' => array('success' => true, 'message' => 'Video updated', 'data' => $sample_youtube_media),
                ),
                array(
                    'id' => 'videos_delete',
                    'name' => 'Delete video',
                    'method' => 'POST',
                    'path' => 'api/mobile/videos/delete/1',
                    'auth' => false,
                    'body_type' => 'none',
                    'sample_request' => array(
                        'path' => 'api/mobile/videos/delete/{id}',
                        'path_example' => 'api/mobile/videos/delete/1',
                    ),
                    'sample_response' => array('success' => true, 'message' => 'Video deleted'),
                ),
                array(
                    'id' => 'videos_reorder',
                    'name' => 'Reorder videos',
                    'method' => 'POST',
                    'path' => 'api/mobile/videos/reorder',
                    'auth' => false,
                    'body_type' => 'json',
                    'body' => array('orders' => array('1' => 10, '2' => 9)),
                    'sample_response' => array('success' => true, 'message' => 'Videos reordered'),
                ),
            ),
        ),
    ),
);
